AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla para crear una instancia EC2 y un grupo de seguridad SSH

Resources:
  TomcatInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-005fc0f236362e99f  
      InstanceType: t2.small
      SecurityGroups:
        - Ref: SecurityGroupSSH
      Tags:
        - Key: Name
          Value: Tomcat

  SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Grupo de seguridad de ssh
      GroupName: GrupoSSH
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  
      Tags: 
        - Key: Name
          Value: GrupoSSH