AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla para crear una instancia EC2 y un grupo de seguridad SSH

Parameters:
  InstanceName:
    Type: String
    Description: Tipo de instancia (t2.small, t2.micro, t2.nano)
    Default: t2.small
    AllowedValues:
      - t2.small
      - t2.micro
      - t2.nano
  InstanceImage:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: ID de la AMI de Ubuntu 22.04
    Default: '/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id'

Resources:
  TomcatInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref InstanceImage
      InstanceType: !Ref InstanceName
      SecurityGroups:
        - Ref: SecurityGroupSSH
      Tags:
        - Key: Name
          Value: Tomcat
      UserData: 
        Fn::Base64: 
          !Sub |
            #!/bin/bash -xe
            exec > /tmp/userdata.log 2>&1
            #====================================================================#
            # PREPARAR BOOTSTRAP DE CFN HELPER SCRIPTS
            #====================================================================#
            apt update -y
            apt install python3-pip -y
            pip3 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
            ln -s /usr/local/init/ubuntu/cfn-hup /etc/init.d/cfn-hup
            #====================================================================#
            #!/bin/bash

            apt update
            apt upgrade -y

            # Desactivación de la pantalla de actualización del kernel

            sed -i "s/#\$nrconf{kernelhints} = -1;/\$nrconf{kernelhints} = -1;/g" /etc/needrestart/needrestart.conf

            # 1. Instalación de Tomcat
            # Creamos un usuario tomcat sin privilegios

            useradd -m -d /opt/tomcat -U -s /bin/false tomcat

            # Instalamos JDK 21

            apt install -y openjdk-21-jdk

            # Instalamos Tomcat 11

            cd /tmp
            wget https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.2/bin/apache-tomcat-11.0.2.tar.gz
            tar -xzf apache-tomcat-11.0.2.tar.gz -C /opt/tomcat --strip-components=1

            # Le damos privilegios al usuario tomcat sobre la aplicación

            chown -R tomcat:tomcat /opt/tomcat/
            chmod -R u+x /opt/tomcat/bin

            # 2. Configuracion de usuarios administrador.

            sed -i '/<\/tomcat-users>/i \
            <role rolename="manager-gui" />\n\
            <user username="manager" password="1234" roles="manager-gui" />\n\
            <role rolename="admin-gui" />\n\
            <user username="admin" password="1234" roles="manager-gui,admin-gui" />' /opt/tomcat/conf/tomcat-users.xml

            # Quitar restricciones a la agina de administrador
            sed -i '/<Valve /,/\/>/ s|<Valve|<!--<Valve|; /<Valve /,/\/>/ s|/>|/>-->|' /opt/tomcat/webapps/manager/META-INF/context.xml
            sed -i '/<Valve /,/\/>/ s|<Valve|<!--<Valve|; /<Valve /,/\/>/ s|/>|/>-->|' /opt/tomcat/webapps/host-manager/META-INF/context.xml

            # 3. Crear un servicio systemd

            # Crear y configurar el archivo tomcat.service 

            echo '[Unit]
            Description=Tomcat
            After=network.target

            [Service]
            Type=forking

            User=tomcat
            Group=tomcat

            Environment="JAVA_HOME=/usr/lib/jvm/java-1.21.0-openjdk-amd64"
            Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom"
            Environment="CATALINA_BASE=/opt/tomcat"
            Environment="CATALINA_HOME=/opt/tomcat"
            Environment="CATALINA_PID=/opt/tomcat/temp/tomcat.pid"
            Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

            ExecStart=/opt/tomcat/bin/startup.sh
            ExecStop=/opt/tomcat/bin/shutdown.sh

            RestartSec=10
            Restart=always

            [Install]
            WantedBy=multi-user.target' | sudo tee /etc/systemd/system/tomcat.service

            # Reiniciamos servicio
            systemctl daemon-reload

            # Iniciamos Tomcat
            systemctl start tomcat

            # Lo habilitamos para que inicie con el sistema
            systemctl enable tomcat



            #====================================================================#
            # Este tiene que ser tu ultima instruccion del script
            # Recuerda modificar el valor del --resource al id lógico de la instancia
            /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource Tomcat --region ${AWS::Region}

  SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Grupo de seguridad de ssh
      GroupName: GrupoSSH
      SecurityGroupIngress: 
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0  
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: 0.0.0.0/0
      Tags: 
      - Key: Name
        Value: GrupoSSH
